# -*- coding: utf-8 -*-
"""DecagonFlow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gh0GE9x_5ygq5GQYgYA4Pc0Bbcn633yy
"""

import numpy as np
import matplotlib.pyplot as plt


def random_decagon(seed, radius=1.0, radial_perturbation=0.25):
    rng = np.random.default_rng(seed)

    number_of_vertices = 10
    angles = np.linspace(
        0.0,
        2.0 * np.pi,
        number_of_vertices,
        endpoint=False
    )

    random_radii = radius * (
        1.0
        + radial_perturbation
        * rng.uniform(-1.0, 1.0, number_of_vertices)
    )

    X = np.column_stack((
        random_radii * np.cos(angles),
        random_radii * np.sin(angles)
    ))

    return X


def second_derivative(X):
    # Use periodic indexing to compute X_{i+1} - X_i.
    edges = np.roll(X, -1, axis=0) - X

    h = np.linalg.norm(edges, axis=1)

    slopes = edges / h[:, None]

    previous_slopes = np.roll(slopes, 1, axis=0)
    previous_h = np.roll(h, 1)

    midpoint_spacing = 0.5 * (previous_h + h)

    # Finite-difference approximation of X_ss.
    X_ss = (
        (slopes - previous_slopes)
        / midpoint_spacing[:, None]
    )

    return X_ss


def stable_dt(X, safety=0.03):
    edges = np.roll(X, -1, axis=0) - X
    h = np.linalg.norm(edges, axis=1)

    return safety * np.min(h) ** 2


def time_step(X, dt):
    return X + dt * second_derivative(X)


def simulate(
    X0,
    number_of_steps=2000,
    save_every=100,
    safety=0.03,
    minimum_edge_length=1e-4
):
    X = X0.copy()

    history = [X.copy()]
    times = [0.0]
    elapsed_time = 0.0

    for step in range(1, number_of_steps + 1):
        # Recalculate dt because the edge lengths change over time.
        dt = stable_dt(X, safety=safety)

        X = time_step(X, dt)
        elapsed_time += dt

        if step % save_every == 0:
            history.append(X.copy())
            times.append(elapsed_time)

        # Stop before neighboring vertices become numerically identical.
        edges = np.roll(X, -1, axis=0) - X
        edge_lengths = np.linalg.norm(edges, axis=1)
        shortest_edge = np.min(edge_lengths)

        if shortest_edge < minimum_edge_length:
            if step % save_every != 0:
                history.append(X.copy())
                times.append(elapsed_time)

            break

    return history, np.asarray(times)


def close_curve(X):
    return np.vstack((X, X[0]))


def plot_all_evolutions(
    all_histories,
    all_times,
    number_of_snapshots=7
):
    number_of_curves = len(all_histories)

    fig, axes = plt.subplots(
        1,
        number_of_curves,
        figsize=(21, 5),
        squeeze=False
    )

    axes = axes[0]

    for curve_number, (history, times, ax) in enumerate(
        zip(all_histories, all_times, axes),
        start=1
    ):
        snapshot_indices = np.linspace(
            0,
            len(history) - 1,
            number_of_snapshots,
            dtype=int
        )

        snapshot_indices = np.unique(snapshot_indices)

        colors = plt.cm.rainbow(
            np.linspace(0.0, 1.0, len(snapshot_indices))
        )

        for color, index in zip(colors, snapshot_indices):
            closed_X = close_curve(history[index])

            ax.plot(
                closed_X[:, 0],
                closed_X[:, 1],
                marker="o",
                markersize=3,
                linewidth=1.0,
                color=color,
                label=f"t = {times[index]:.4f}"
            )

        ax.set_title(f"Random decagon {curve_number}")
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.set_aspect("equal")
        ax.grid(True, alpha=0.3)

        ax.legend(
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),
            fontsize=8,
            borderaxespad=0
        )

    fig.suptitle(
        "Curve evolution of three random decagons",
        fontsize=15
    )

    fig.subplots_adjust(
        left=0.05,
        right=0.97,
        bottom=0.12,
        top=0.85,
        wspace=0.75
    )

    plt.show()


def plot_snapshot_grid(
    all_histories,
    all_times,
    number_of_snapshots=6
):
    number_of_curves = len(all_histories)

    fig, axes = plt.subplots(
        number_of_curves,
        number_of_snapshots,
        figsize=(
            3.2 * number_of_snapshots,
            3.2 * number_of_curves
        ),
        constrained_layout=True,
        squeeze=False
    )

    colors = plt.cm.rainbow(
        np.linspace(0.0, 1.0, number_of_snapshots)
    )

    for row, (history, times) in enumerate(
        zip(all_histories, all_times)
    ):
        snapshot_indices = np.linspace(
            0,
            len(history) - 1,
            number_of_snapshots,
            dtype=int
        )

        initial_limit = 1.25 * np.max(
            np.linalg.norm(history[0], axis=1)
        )

        for column, (index, color) in enumerate(
            zip(snapshot_indices, colors)
        ):
            ax = axes[row, column]
            closed_X = close_curve(history[index])

            ax.plot(
                closed_X[:, 0],
                closed_X[:, 1],
                marker="o",
                linestyle="-",
                color=color,
                linewidth=1.0,
                markersize=3
            )

            ax.set_xlim(-initial_limit, initial_limit)
            ax.set_ylim(-initial_limit, initial_limit)
            ax.set_aspect("equal")
            ax.grid(True, alpha=0.25)
            ax.set_title(f"t = {times[index]:.4f}")

            if column == 0:
                ax.set_ylabel(f"Decagon {row + 1}\ny")

            if row == number_of_curves - 1:
                ax.set_xlabel("x")

    fig.suptitle(
        "Three random decagons at multiple time steps",
        fontsize=16
    )

    plt.show()


if __name__ == "__main__":
    seeds = [10, 20, 30]

    initial_decagons = [
        random_decagon(
            seed=seed,
            radius=1.0,
            radial_perturbation=0.30
        )
        for seed in seeds
    ]

    all_histories = []
    all_times = []

    for decagon_number, X0 in enumerate(
        initial_decagons,
        start=1
    ):
        history, times = simulate(
            X0,
            number_of_steps=2000,
            save_every=100,
            safety=0.03,
            minimum_edge_length=1e-4
        )

        all_histories.append(history)
        all_times.append(times)

        print(
            f"Decagon {decagon_number}: "
            f"{len(history)} saved states, "
            f"final simulated time = {times[-1]:.6f}"
        )

    # Figure 1:
    plot_all_evolutions(
        all_histories,
        all_times,
        number_of_snapshots=7
    )
    # Figure 2:
    plot_snapshot_grid(
        all_histories,
        all_times,
        number_of_snapshots=6
    )